import streamlit as st
import pandas as pd
import json
import os
import subprocess
import time

# --- Pager Settings ---
st.set_page_config(page_title="Ransomware Defend Control Center", layout="wide", initial_sidebar_state="expanded")

# Inject Custom Dark Theme Aesthetic
st.markdown("""
<style>
    .stApp {
        background-color: #0E1117;
        color: #C6D0F5;
    }
    .metric-container {
        background-color: #1a1a2e;
        padding: 15px;
        border-radius: 10px;
        border-left: 5px solid #e94560;
    }
</style>
""", unsafe_allow_html=True)

st.title("🛡️ Ransomware Early Detection Dashboard")
st.markdown("XAI-Driven Behavioral Analysis & Immutable Blockchain Auditing")
st.divider()

# --- Sidebar Controls ---
with st.sidebar:
    st.header("💻 Terminal Execution")
    st.info("Run the independent modules in your local terminals to monitor and simulate attacks.")
    
    st.markdown("**1. Start the Live Guard:**")
    st.code("py detection/realtime_detector.py", language="bash")
    
    st.markdown("**2. Simulate Hacker Payload:**")
    st.code("py simulation/file_activity_simulator.py", language="bash")
    
    st.markdown("**3. Restore Environment:**")
    st.code("py simulation/file_restore_tool.py", language="bash")
    
    st.divider()
    st.caption("Auto-refreshing live dashboard every 2 seconds...")


# --- Main Dashboard Tabs ---
tab1, tab2, tab3 = st.tabs(["📊 Live Monitoring", "🔗 Blockchain Ledger", "🧠 XAI Details"])

# Tab 1: Live Monitoring
with tab1:
    col_chart, col_alerts = st.columns([2, 1])
    
    with col_chart:
        st.subheader("System Entropy Timeline")
        
        # Try to load live timeline JSON generated by the detector
        if os.path.exists("live_timeline.json"):
            try:
                df_live = pd.read_json("live_timeline.json")
                if not df_live.empty:
                    # Plot natively in streamlit using a line chart
                    df_live['time_index'] = df_live['time'] - df_live['time'].min()
                    st.line_chart(df_live.set_index("time_index")["entropy"], use_container_width=True)
                else:
                    st.info("No timeline data recorded yet. Run simulator.")
            except:
                st.info("Awaiting live timeline sync...")
        else:
            # Fallback to PNG
            if os.path.exists("detection/realtime_timeline.png"):
                st.image("detection/realtime_timeline.png", caption="Last Recorded Timeline", use_container_width=True)
            elif os.path.exists("realtime_timeline.png"):
                st.image("realtime_timeline.png", caption="Last Recorded Timeline", use_container_width=True)
            else:
                 st.info("Timeline sync pending start of detector.")

    with col_alerts:
        st.subheader("🚨 Live Threat Map")
        # Dynamically map recent blocks to physical front-end notifications
        if os.path.exists("blockchain_ledger.json"):
            try:
                with open("blockchain_ledger.json", "r") as f:
                    ledger = json.load(f)
                    # Filter out genesis string, keep only dictionary payloads
                    attacks = [b for b in reversed(ledger) if isinstance(b.get('event_data'), dict)]
                    
                    if attacks:
                        st.error(f"**{len(attacks)} Malicious Encryptions Intercepted!**", icon="🛑")
                        for att in attacks[:4]: # Display top 4 recent notifications
                            fname = att['event_data'].get('file', 'Unknown')
                            ent = att['event_data'].get('entropy', 'N/A')
                            st.warning(f"**File:** `{fname}`\n\n**Entropy Spike:** `{ent}`", icon="⚠️")
                    else:
                        st.success("System Secure. No active threats.", icon="🛡️")
            except:
                st.success("System Secure. No active threats.", icon="🛡️")
        else:
            st.success("System Secure. No active threats.", icon="🛡️")


# Tab 2: Blockchain Ledger
with tab2:
    st.subheader("Immutable Audit Trail (SHA-256)")
    if os.path.exists("blockchain_ledger.json"):
        with open("blockchain_ledger.json", "r") as f:
            try:
                ledger = json.load(f)
                
                # Convert list of dicts to dataframe for beautiful table rendering
                # Flatten the data structure slightly
                flat_ledger = []
                for b in reversed(ledger):
                    val = b['event_data']
                    details = val if isinstance(val, str) else f"File: {val.get('file', '')} | Entropy: {val.get('entropy', '')}"
                    
                    flat_ledger.append({
                        "Block #": b['index'],
                        "Timestamp": time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(b['timestamp'])),
                        "Event": details,
                        "Hash": b['hash'][:16] + "..." # Truncated for display
                    })
                
                st.dataframe(pd.DataFrame(flat_ledger), use_container_width=True, hide_index=True)
            
            except json.JSONDecodeError:
                st.warning("Blockchain ledger is currently syncing or unreadable.")
    else:
        st.info("No recorded attacks in Blockchain. Ledger is clean.")

# Tab 3: XAI
with tab3:
    st.subheader("Game Theory (SHAP) Matrix Evaluation")
    
    col1, col2 = st.columns([1, 2])
    with col1:
        st.markdown("""
        **Behavioral Feature Weights:**
        - **Entropy:** Represents cryptographic disorder.
        - **Rename Frequency:** Represents mass-extension mapping (`.locked`).
        - **File Activity:** Represents IO manipulation speeds.
        """)
    with col2:
        if os.path.exists("detection/shap_summary.png"):
            st.image("detection/shap_summary.png", use_container_width=True)
        elif os.path.exists("shap_summary.png"):
            st.image("shap_summary.png", use_container_width=True)
        else:
            st.info("Run the detector to validate a ransomware payload and generate the SHAP global matrix.")

# --- Auto Refresh Logic ---
# Sleep briefly and Rerun script to continuously poll for live json/ledger updates
time.sleep(2)
st.rerun()
